{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Response size per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg (rate(fastapi_http_server_response_size_bytes_sum[$__rate_interval]) / rate(fastapi_http_server_response_size_bytes_count[$__rate_interval])) by(http_target)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(exported_job) (rate(fastapi_http_server_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request execution time in milliseconds (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(fastapi_http_server_duration_milliseconds_sum[$__rate_interval]) / rate(fastapi_http_server_duration_milliseconds_count[$__rate_interval])) by(http_target)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response size per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg (rate(fastapi_http_server_response_size_bytes_sum[$__rate_interval]) / rate(fastapi_http_server_response_size_bytes_count[$__rate_interval])) by(exported_job) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request execution time in milliseconds (95 percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_target) (rate(fastapi_http_server_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}