filebeat.inputs:
- type: container
  paths: 
    - /var/lib/docker/containers/*/*.log

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: elastic
  password: y1Qbyl*UblzHSk3hks9h
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"