receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

# exporters:
#   elasticsearch:
#     endpoints: ["http://elasticsearch:9200"]
#     logs_index: "logs-apm"
#     traces_index: "traces-apm"
#     metrics_index: "metrics-apm"
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: fastapi
  # debug:
  #   verbosity: detailed
  logging:
    loglevel: debug
  # elasticsearch/apm:
  otlp/elastic:
    endpoint: "http://apm-server:8200"
    # endpoints: ["http://apm-server:8200"]  # APM Server HTTP API
    tls:
      insecure: true
    # traces_endpoint: "intake/v2/events"
    # metrics_endpoint: "intake/v2/metrics"

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      # processors: [batch]
      # exporters: [elasticsearch]
      exporters: [logging, otlp/elastic]  # Отправка в APM Server вместо прямого в ES
    metrics:
      receivers: [otlp]
      # processors: [batch]
      exporters: [logging, otlp/elastic, prometheus]
    logs:
      receivers: [otlp]
      # processors: [batch]
      exporters: [logging, otlp/elastic]  # Отправка в APM Server вместо прямого в ES
      # exporters: [elasticsearch]